# Generated by Django 5.1.2 on 2024-10-10 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='رنگ ها')),
            ],
            options={
                'verbose_name': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='طرح ها')),
            ],
            options={
                'verbose_name': 'طرح ها',
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('rectangle', 'مستطیل'), ('circle', 'دایره')], max_length=50, verbose_name='شکل')),
            ],
            options={
                'verbose_name': 'شکل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Carpet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='Unknown', max_length=100, verbose_name='فرش ها')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='طول')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='عرض')),
                ('radius', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='شعاع')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpets.color', verbose_name='رنگ')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpets.design', verbose_name='طرح')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpets.shape', verbose_name='شکل')),
            ],
            options={
                'verbose_name': 'فرش ها',
            },
        ),
    ]
