# Generated by Django 5.1.2 on 2024-10-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpet',
            name='length',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='radius',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='width',
        ),
    ]
