# Generated by Django 5.1.2 on 2024-10-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0002_remove_carpet_length_remove_carpet_radius_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Length',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='طول')),
            ],
            options={
                'verbose_name': 'طول',
            },
        ),
        migrations.CreateModel(
            name='Radius',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='شعاع')),
            ],
            options={
                'verbose_name': 'شعاع',
            },
        ),
        migrations.CreateModel(
            name='Width',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='عرض')),
            ],
            options={
                'verbose_name': 'عرض',
            },
        ),
        migrations.AddField(
            model_name='carpet',
            name='length',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpets.length', verbose_name='طول'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='radius',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpets.radius', verbose_name='شعاع'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='width',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpets.width', verbose_name='عرض'),
        ),
    ]
