# Generated by Django 5.1.2 on 2024-10-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0004_carpet_is_rectangle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpet',
            name='shape',
        ),
    ]
