# Generated by Django 5.1.2 on 2024-10-12 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_workers_section'),
        ('carpets', '0005_remove_carpet_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpet',
            name='cheleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheleh_carpets', to='accounts.workers', verbose_name='چله'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='chelehkhoroug',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carpet',
            name='chellehvouroud',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carpet',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='کد'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='ersalshodeh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carpet',
            name='gereh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gereh_carpets', to='accounts.workers', verbose_name='گره'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='gerehvouroud',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carpet',
            name='grehkhoroug',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carpet',
            name='id_name',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='carpet',
            name='metraj',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='متراژ'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='serial',
            field=models.CharField(default=1, max_length=30, verbose_name='سریال'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='shirazeh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirazeh_carpets', to='accounts.workers', verbose_name='شیرازه'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='shirazehkhoroug',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carpet',
            name='shirazehvouroud',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
