# Generated by Django 5.1.2 on 2024-10-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0006_carpet_cheleh_carpet_chelehkhoroug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpet',
            old_name='width',
            new_name='arz',
        ),
        migrations.RenameField(
            model_name='carpet',
            old_name='design',
            new_name='naghsheh',
        ),
        migrations.RenameField(
            model_name='carpet',
            old_name='color',
            new_name='rang',
        ),
        migrations.RenameField(
            model_name='carpet',
            old_name='length',
            new_name='tool',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='radius',
        ),
    ]
