# Generated by Django 5.1.2 on 2024-10-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0007_rename_width_carpet_arz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpet',
            old_name='is_rectangle',
            new_name='isrectangle',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='id_name',
        ),
    ]
