# Generated by Django 5.1.2 on 2024-10-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0008_rename_is_rectangle_carpet_isrectangle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpet',
            name='chelehkhoroug',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='chellehvouroud',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='gerehvouroud',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='grehkhoroug',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='shirazehkhoroug',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='shirazehvouroud',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
