# Generated by Django 5.1.2 on 2024-10-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0011_carpet_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpet',
            old_name='chelehkhoroug',
            new_name='chelehKhoroug',
        ),
        migrations.RenameField(
            model_name='carpet',
            old_name='chellehvouroud',
            new_name='chellehVouroud',
        ),
        migrations.RenameField(
            model_name='carpet',
            old_name='gerehvouroud',
            new_name='gerehVouroud',
        ),
        migrations.RenameField(
            model_name='carpet',
            old_name='grehkhoroug',
            new_name='grehKhoroug',
        ),
        migrations.RenameField(
            model_name='carpet',
            old_name='isrectangle',
            new_name='isRectangle',
        ),
        migrations.RenameField(
            model_name='carpet',
            old_name='shirazehkhoroug',
            new_name='shirazehKhoroug',
        ),
        migrations.RenameField(
            model_name='carpet',
            old_name='shirazehvouroud',
            new_name='shirazehVouroud',
        ),
    ]
