# Generated by Django 5.1.2 on 2024-10-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0013_remove_carpet_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='سال')),
                ('months', models.JSONField(default=dict, verbose_name='ماه\u200cها')),
            ],
            options={
                'verbose_name': 'سال\u200cها',
            },
        ),
    ]
