# Generated by Django 5.1.2 on 2024-10-14 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0014_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='months',
        ),
    ]
