# Generated by Django 5.1.2 on 2024-10-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0015_remove_year_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='value',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='ماه'),
        ),
    ]
