# Generated by Django 5.1.2 on 2024-10-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0019_remove_month_carpets_month_carpets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='carpets',
        ),
        migrations.AddField(
            model_name='month',
            name='carpets',
            field=models.ManyToManyField(blank=True, null=True, related_name='carpet_month', to='carpets.carpet'),
        ),
    ]
