# Generated by Django 5.1.2 on 2024-10-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0021_alter_month_carpets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
