# Generated by Django 5.1.2 on 2024-10-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0022_delete_month_delete_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='length',
            name='value',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='طول'),
        ),
    ]
