# Generated by Django 5.1.2 on 2024-10-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0023_alter_length_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpet',
            name='metraj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='طول'),
        ),
        migrations.AlterField(
            model_name='width',
            name='value',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='عرض'),
        ),
    ]
