# Generated by Django 5.1.2 on 2024-10-16 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0025_alter_carpet_metraj'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carpet',
        ),
    ]
