# Generated by Django 5.1.2 on 2024-10-16 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0027_carpet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carpet',
        ),
    ]
