# Generated by Django 5.1.2 on 2024-10-16 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_help'),
        ('carpets', '0028_delete_carpet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isRectangle', models.BooleanField(default=True, verbose_name='مستطیل')),
                ('metraj', models.CharField(blank=True, max_length=20, null=True, verbose_name='متراژ')),
                ('serial', models.CharField(default=1, max_length=30, verbose_name='سریال')),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name='کد')),
                ('shirazehKhoroug', models.CharField(blank=True, max_length=40, null=True)),
                ('chelehKhoroug', models.CharField(blank=True, max_length=40, null=True)),
                ('grehKhoroug', models.CharField(blank=True, max_length=40, null=True)),
                ('shirazehVouroud', models.CharField(blank=True, max_length=40, null=True)),
                ('chellehVouroud', models.CharField(blank=True, max_length=40, null=True)),
                ('gerehVouroud', models.CharField(blank=True, max_length=40, null=True)),
                ('ersalshodeh', models.BooleanField(default=False)),
                ('arz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpets.width', verbose_name='عرض')),
                ('cheleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheleh_carpets', to='accounts.workers', verbose_name='چله')),
                ('gereh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gereh_carpets', to='accounts.workers', verbose_name='گره')),
                ('naghsheh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpets.design', verbose_name='طرح')),
                ('rang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpets.color', verbose_name='رنگ')),
                ('shirazeh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirazeh_carpets', to='accounts.workers', verbose_name='شیرازه')),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpets.length', verbose_name='طول')),
            ],
            options={
                'verbose_name': 'فرش ها',
            },
        ),
    ]
