# Generated by Django 5.1.2 on 2024-10-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0030_remove_carpet_cheleh_remove_carpet_gereh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpet',
            name='cheleh',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شیرازه'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='gereh',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شیرازه'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='shirazeh',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شیرازه'),
        ),
    ]
