# Generated by Django 5.1.2 on 2024-10-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0031_carpet_cheleh_carpet_gereh_carpet_shirazeh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpet',
            name='arz',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='naghsheh',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='rang',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='tool',
        ),
        migrations.AlterField(
            model_name='carpet',
            name='cheleh',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='چله'),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='gereh',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='گره'),
        ),
    ]
