# Generated by Django 5.1.2 on 2024-10-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0032_remove_carpet_arz_remove_carpet_naghsheh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpet',
            name='arz',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='عرض'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='naghsheh',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='نقشه'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='rang',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='tool',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='طول'),
        ),
    ]
