# Generated by Django 5.1.2 on 2024-10-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_workers_alter_sectionuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
