# Generated by Django 5.1.2 on 2024-10-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_workers_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='section',
        ),
    ]
