# Generated by Django 5.1.2 on 2024-10-11 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_workers_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'طرح ها'},
        ),
        migrations.AlterModelOptions(
            name='sectionuser',
            options={'verbose_name': 'بخش و کارمند'},
        ),
        migrations.AlterModelOptions(
            name='workers',
            options={'verbose_name': 'کارمندان'},
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100, verbose_name='بخش ها'),
        ),
        migrations.AlterField(
            model_name='sectionuser',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.section', verbose_name='بخش'),
        ),
        migrations.AlterField(
            model_name='sectionuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workers', verbose_name='کارمند'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نام'),
        ),
    ]
