# Generated by Django 5.1.2 on 2024-10-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_section_options_alter_sectionuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'بخش ها'},
        ),
    ]
