# Generated by Django 5.1.2 on 2024-10-12 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_section_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='accounts.section'),
        ),
    ]
