# Generated by Django 5.1.2 on 2024-10-14 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_name_section_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(verbose_name='مبلغ')),
                ('date', models.CharField(max_length=30, verbose_name='تاریخ ')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workers', verbose_name='نام کارمند')),
            ],
            options={
                'verbose_name': 'مساعده',
            },
        ),
    ]
